### PR TITLE
Move cmd/ingest to internal/ingest

### PR DESCRIPTION
**Pull request by mhemmings**
Move ingest functionality from cmd. We will create a charm-ingest command in next PR.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/243/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/244/

**Review by rogpeppe — APPROVED** [review]
LGTM, thanks.

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by mhemmings** [comment]
:shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/245/

**Pull request merged**
