### PR TITLE
cmd/charm: use an older docker client version by default

### PR DESCRIPTION
**Pull request by mhilton**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/220/

**Review by rogpeppe — APPROVED** [review]
LGTM, thanks.

**Review by fabricematrat — APPROVED** [review]

**Comment by mhilton** [comment]
:shipit: $$merge$$

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
