### PR TITLE
Add terms-client and plans-client subcommands.

### PR DESCRIPTION
**Pull request by cmars**
Build terms and plans subcommands into charmstore-client, avoiding the execution overhead introduced by enumerating over plugin.

Some changes here are due to dependency requirements of these new subcommands; newer versions of loggo and cmd have changed the command output slightly, which required updating tests.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/183/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/184/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/185/

**Review by mhilton — APPROVED** [review]
LGTM

**Comment by cmars** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
