### PR TITLE
Updated the dependencies.tsv

### PR DESCRIPTION
**Pull request by vinu2003**
Updated the dependencies.tsv to reflect the charmVersion changes

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/221/

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/222/

**Review by wallyworld — APPROVED** [review]

**Comment by vinu2003** [comment]
$$merge$$

**Comment by vinu2003** [comment]
..shipit..

**Comment by wallyworld** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
