### PR TITLE
add --resource to charm push

### PR DESCRIPTION
**Pull request by natefinch**
same as https://github.com/CanonicalLtd/charmstore-client/pull/206

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore-client/7/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore-client/9/
Test PASSed.

**Comment by natefinch** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
