### PR TITLE
add --resource flag to charm publish

### PR DESCRIPTION
**Pull request by natefinch**
same as https://github.com/CanonicalLtd/charmstore-client/pull/200

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore-client/6/
Test PASSed.

**Comment by natefinch** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-client-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/charmstore-client-merge/1

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
