### PR TITLE
cmd/charm: use browser-based login by default

### PR DESCRIPTION
**Pull request by mhilton**
This resolves issue #44

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/223/

**Review by frankban — APPROVED** [review]
Looks good, is there a way to test it?

**Review by fabricematrat — APPROVED** [review]

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
