### PR TITLE
Replace development channel with edge.

### PR DESCRIPTION
**Pull request by frankban**
This is a mechanical branch, except for fixing the tests that
needed to be updated for the new dependencies.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore-client/118/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by frankban** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
