### PR TITLE
Whitelist plans subcommands.

### PR DESCRIPTION
**Pull request by cmars**
See also juju/charm-tools#378

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/182/

**Review by rogpeppe — APPROVED** [review]
LGTM, (assuming you've got the command names right!)

**Comment by cmars** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
