### PR TITLE
Fixes the "No X found." responses.

### PR DESCRIPTION
**Pull request by alesstimec**
A drive by of an unpredictable charm terms response - now sorting terms to make responses
and tests more predictable.

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore-client/44/
Test PASSed.

**Comment by urosj** [comment]
:+1: QA :ok:

**Comment by fabricematrat** [comment]
:+1:

**Comment by alesstimec** [comment]
:shipit:

**Comment by alesstimec** [comment]
$$merge$$

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
