### PR TITLE
change push resource to attach

### PR DESCRIPTION
**Pull request by natefinch**
same as https://github.com/CanonicalLtd/charmstore-client/pull/210

### CODE REVIEW

**Comment by jujugui** [comment]
please test this

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/charmstore-client/8/
Test PASSed.

**Comment by natefinch** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
