### PR TITLE
deps.tsv: Use latest plans client

### PR DESCRIPTION
**Pull request by mattyw**

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/191/

**Review by tasdomas — APPROVED** [review]

**Review by alesstimec — APPROVED** [review]

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
