### PR TITLE
cmd/charm: update push help to refer to release command

### LINKED ISSUE #140: charm push help references charm publish subcommand which no longer exists.
> charm push -h

```
...
The pushed charm or bundle is unpublished and therefore usually only available
to a restricted set of users. See the publish command for info on how to make
charms and bundles available to others.
...
```

This should be updated to reference `charm release`.

### PR DESCRIPTION
**Pull request by mhilton**
This fixes #140

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/224/

**Review by rogpeppe — APPROVED** [review]
LGTM ta

**Comment by mhilton** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
