### PR TITLE
Update plans-client dependency with UX improvements.

### PR DESCRIPTION
**Pull request by cmars**
Better messages on "unauthorized" errors. See juju/plans-client#3.

### CODE REVIEW

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/charmstore-client/186/

**Review by rogpeppe — APPROVED** [review]
LGTM

**Comment by mhilton** [comment]
LGTM

**Comment by cmars** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
