### PR TITLE
remove [Service] from list-resource output

### PR DESCRIPTION
**Pull request by jrwren**

### CODE REVIEW

**Comment by jrwren** [comment]
address https://github.com/juju/charmstore-client/issues/123 and 

https://github.com/juju/charmstore-client/issues/122

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore-client/170/

**Comment by jrwren** [comment]
short format was requested by @mbruzek via irc and seems simple enough to just do it.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/charmstore-client/171/

**Comment by mbruzek** [comment]
I have reviewed the code and am +1 to this change. Thank you for asking about it on irc!

**Review by fabricematrat — APPROVED** [review]

**Review by bac — APPROVED** [review]

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/charmstore-client-merge

**Pull request merged**
